namespace TuiEdit;

/// <summary>Represents an editor command derived from a key press or menu.</summary>
internal enum EditorCommand
{
    None,
    MoveLeft, MoveRight, MoveUp, MoveDown,
    GoHome, GoEnd,
    GoDocStart, GoDocEnd,
    PageUp, PageDown,
    WordLeft, WordRight,
    DelWordBefore, DelWordAfter,
    /// <summary>
    /// Saves the file. Prompts for a name when the file is still unnamed
    /// (behaves like <see cref="SaveAs"/>).
    /// </summary>
    Save,
    SaveAs,
    SaveAll,
    FileFormat,
    TrimTrailing,
    /// <summary>Quits (confirms when there are unsaved changes).</summary>
    Quit,
    NewFile,
    OpenFile,
    OpenRecent,
    About,
    Help,
    Settings,
    CommandPalette,
    QuickOpen,
    CommandLine,
    ToggleMenu,
    OpenMenuFile, OpenMenuEdit, OpenMenuHelp,
    Find,
    FindNext,
    FindPrev,
    GoToDefinition,
    Replace,
    GoToLine,
    DocStats,
    Grep,
    CutLine, CopyLine, Paste,
    RegisterPick,
    DuplicateLine,
    ToggleComment,
    GoBracketMatch,
    SortLines,
    ShellFilter,
    SurroundAdd,
    SurroundChange,
    SurroundDelete,
    ToggleBookmark, NextBookmark,
    CompleteWord,
    ToggleFold,
    MoveLineUp, MoveLineDown,
    Undo, Redo,
    InsertEnter, InsertBackspace, InsertDelete, InsertTab, InsertChar,
    Unindent,
    SelectAll,
    ToggleLineNumbers,
    ToggleWrap,
    ToggleWhitespace,
    ToggleSidebar,
    NewTab,
    /// <summary>Closes the tab (prompts via dialog when dirty).</summary>
    CloseTab,
    /// <summary>Switches to the next/previous tab (Ctrl+Tab where the terminal passes it through).</summary>
    NextTab, PrevTab,
    GoTabNumber,
    ListTabs,
    JumpBack,
    JumpForward,
    SplitPane,
    NextPane, PrevPane,
    GoPaneNumber,
    CaretAddAbove,
    CaretAddBelow,
    CaretAddNext,
    CaretClear,
}
